name: 설정 불러오기
description: 각종 설정을 불러온다
runs:
  using: 'composite'
  steps:

    - name: JDK 설정
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: properties 불러오기
      run: |
        echo "${{ env.BRANCH }}"
        echo "${{ secrets.KAKAO_PROPERTIES }}" > ./src/main/resources/application-kakao.properties
        echo "${{ secrets.OBJECT_STORAGE_PROPERTIES }}" > ./src/main/resources/application-object-storage.properties
        
        if [ "${{ env.BRANCH }}" == "release" ]; then
          echo "${{ secrets.RELEASE_PROPERTIES }}" > ./src/main/resources/application-release.properties
        elif [ "${{ env.BRANCH }}" == "master" ]; then
          echo "${{ secrets.MASTER_PROPERTIES }}" > ./src/main/resources/application-deploy.properties
        fi
      shell: bash
