on:
  push:
    branches: [ release, master ]

jobs:

  branch:
    runs-on: ubuntu-latest

    steps:
      - name: 브랜치 가져오고 포트 설정하기
        run: |
          if [ "${{ env.BRANCH }}" == "master" ]; then
            echo "PORT=443" >> $GITHUB_ENV
          elif [ "${{ env.BRANCH }}" == "release" ]; then
            echo "PORT=8080" >> $GITHUB_ENV
          fi

  load:
    uses: ./.github/workflows/load.yaml

  build:
    runs-on: ubuntu-latest
    needs: [ branch, load ]

    steps:
      - name: 테스트 및 빌드
        run: ./gradlew clean build -Pprofile="${{ env.BRANCH }}"

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/zelkova/new

      - name: SSH 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script_stop: true
          scripts: |
            rm -rf /home/ubuntu/zelkova/"${{ env.BRANCH }}"/current
            mkdir /home/ubuntu/zelkova/"${{ env.BRANCH }}"/current
            mv /home/ubuntu/zelkova/new/project.jar /home/ubuntu/zelkova/"${{ env.BRANCH }}"/current/project.jar
            cd /home/ubuntu/zelkova/"${{ env.BRANCH }}"/current
            sudo fuser -k -n tcp "$PORT" || true
            nohup java -jar project.jar --server.port="$PORT" > ./output.log 2>&1 &
            rm -rf /home/ubuntu/zelkova/new
