name: load

on:
  workflow_call:

jobs:
  branch:
    runs-on: ubuntu-latest

    steps:
      - name: 브랜치 가져오기
        run: |
          branch=${{ github.base_ref || github.ref_name }}
          echo "BRANCH=${branch}" >> $GITHUB_ENV
          echo "${{ env.BRANCH }}"

  load:
    runs-on: ubuntu-latest
    needs: branch

    steps:
      - name: repository 불러오기
        uses: actions/checkout@v4

      - name: JDK 설정
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: properties 불러오기
        run: |
          echo "${{ secrets.KAKAO_PROPERTIES }}" > ./src/main/resources/application-kakao.properties
          echo "${{ secrets.OBJECT_STORAGE_PROPERTIES }}" > ./src/main/resources/application-object-storage.properties
          
          if [ "${{ env.BRANCH }}" == "release" ]; then
            echo "${{ secrets.RELEASE_PROPERTIES }}" > ./src/main/resources/application-release.properties
          elif [ "${{ env.BRANCH }}" == "master" ]; then
            echo "${{ secrets.MASTER_PROPERTIES }}" > ./src/main/resources/application-deploy.properties
          fi
