on:
  pull_request:
    branches: [ develop, release, master ]

jobs:
  load:
    uses: ./.github/workflows/load.yaml

  test:
    runs-on: ubuntu-latest
    needs: [ load ]

    steps:
      - name: 테스트
        run: |
          if [ "${{ env.BRANCH }}" ]; then
            ./gradlew test -Pprofile="${{ env.BRANCH }}"
          else
            ./gradlew test
          fi
