on:
  pull_request:
    branches: [ develop, release, master ]

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/branch
      - uses: ./.github/actions/load

  test:
    runs-on: ubuntu-latest
    needs: load

    steps:
      - name: 테스트
        env:
          BRANCH: ${{ needs.branch.outputs.branch }}
        run: |
          if [ $BRANCH ]; then
            ./gradlew test -Pprofile=$BRANCH
          else
            ./gradlew test
          fi
